const lesCartes = [
    { id: 1, name: "Gin Blossoms", rarity: "common", icon: "assets/GinBlossoms.jpg"},
    { id: 2, name: "ZZ Top", rarity: "common", icon: "assets/ZZTOP.jpg" },
    { id: 3, name: "The Cranberries", rarity: "common", icon: "assets/Cranberries.jpg" },
    { id: 4, name: "Billy Idol", rarity: "common", icon: "assets/BillyIdol.jpg" },
    { id: 5, name: "Alice Cooper", rarity: "common", icon: "assets/AliceCooper.jpg"},
    { id: 6, name: "Boston", rarity: "common", icon: "assets/Boston.jpg"},
    { id: 7, name: "Blink-182", rarity: "common", icon: "assets/blink182.jpg"},
    { id: 8, name: "Ed Sheeran", rarity: "common", icon: "assets/EdSheeran.jpg"},
    { id: 9, name: "Evanescence", rarity: "common", icon: "assets/evanescence.jpg" },
    { id: 10, name: "Foo Fighters", rarity: "common", icon: "assets/FooFighers.jpg"},
    { id: 11, name: "Heart", rarity: "common", icon: "assets/Heart.jpg"},
    { id: 12, name: "R.E.M", rarity: "common", icon: "assets/REM.jpg" },
    { id: 13, name: "Simon & Garfunkel", rarity: "common", icon: "assets/SimonGarfunkel.jpg"},
    { id: 14, name: "Twisted Sister", rarity: "common", icon: "assets/TwistedSister.jpg" },
    { id: 15, name: "System Of A Down", rarity: "common", icon: "assets/SystemOfDown.jpg" },
    { id: 16, name: "ABBA", rarity: "common", icon: "assets/abba.jpg"},
    { id: 17, name: "Black Sabbath", rarity: "common", icon: "assets/blacksabbath.jpg" },
    { id: 18, name: "Britney Spears", rarity: "common", icon: "assets/britneyspears.jpg" },
    { id: 19, name: "Bruce Springsteen", rarity: "common", icon: "assets/brucspringsteen.jpg" },
    { id: 20, name: "BTS", rarity: "common", icon: "assets/bts.jpg" },
    { id: 21, name: "Chuck Berry", rarity: "common", icon: "assets/chuckberry.png"},
    { id: 22, name: "David Bowie", rarity: "common", icon: "assets/davidbowie.jpg" },
    { id: 23, name: "Dire Straits", rarity: "common", icon: "assets/direstrait.jpg"},
    { id: 24, name: "Iron Maiden", rarity: "common", icon: "assets/ironmaiden.jpg" },
    { id: 25, name: "The Kinks", rarity: "common", icon: "assets/kinks.jpg"},
    { id: 26, name: "Lady Gaga", rarity: "common", icon: "assets/ladygaga.jpg" },
    { id: 27, name: "My Chemical Romances", rarity: "common", icon: "assets/mychemicalromance.jpg" },
    { id: 28, name: "Megadeth", rarity: "common", icon: "assets/megadeth.jpg"},
    { id: 29, name: "Mariah Carey", rarity: "common", icon: "assets/mariahcarey.jpg" },
    { id: 30, name: "Mötley Crue", rarity: "common", icon: "assets/motleycrue.jpg" },
    { id: 31, name: "P!nk", rarity: "common", icon: "assets/p!nk.jpg"},
    { id: 32, name: "Pantera", rarity: "common", icon: "assets/pantera.jpg" },
    { id: 33, name: "Pearl Jam", rarity: "common", icon: "assets/pearljam.jpg"},
    { id: 34, name: "Phil Collins", rarity: "common", icon: "assets/philcollins.jpg"},
    { id: 35, name: "Shakira", rarity: "common", icon: "assets/shakira.jpg"},
    { id: 36, name: "Slipknot", rarity: "common", icon: "assets/slipknot.jpg"},
    { id: 37, name: "Sum41", rarity: "common", icon: "assets/sum41.jpg" },
    { id: 38, name: "Survivor", rarity: "common", icon: "assets/survivor.jpg" },
    { id: 39, name: "TALK", rarity: "common", icon: "assets/talk.jpg" },
    { id: 40, name: "The Killers", rarity: "common", icon: "assets/thekillers.jpg"},
    { id: 41, name: "The Who", rarity: "common", icon: "assets/thewho.jpg" },
    { id: 42, name: "Toto", rarity: "common", icon: "assets/toto.jpg"},
    { id: 43, name: "Van Halen", rarity: "common", icon: "assets/Boston.jpg" },

    // RARE
    { id: 51, name: "Nirvana", rarity: "rare", icon: "assets/nirvana.jpg" },
    { id: 52, name: "U2", rarity: "rare", icon: "assets/U2.jpg" },
    { id: 53, name: "Bryan Adams", rarity: "rare", icon: "assets/BryanAdams.jpg"},
    { id: 54, name: "Roxette", rarity: "rare", icon: "assets/Roxette.jpg" },
    { id: 55, name: "Def Leppard", rarity: "rare", icon: "assets/DefLeppard.jpg" },
    { id: 56, name: "Gun N' Roses", rarity: "rare", icon: "assets/gunNrose.jpg" },
    { id: 57, name: "Journey", rarity: "rare", icon: "assets/journey.jpg" },
    { id: 58, name: "KISS", rarity: "rare", icon: "assets/kiss.jpg" },
    { id: 59, name: "Poison", rarity: "rare", icon: "assets/poison.jpg"},
    { id: 60, name: "Scorpions", rarity: "rare", icon: "assets/scorpions.jpg" },
    { id: 61, name: "Shania Twain", rarity: "rare", icon: "assets/shaniatwain.jpg" },
    { id: 62, name: "The Beach Boys", rarity: "rare", icon: "assets/beachboy.jpg" },
    { id: 63, name: "Billy Joel", rarity: "rare", icon: "assets/billyjoel.jpg"},
    { id: 64, name: "Bruno Mars", rarity: "rare", icon: "assets/brunomars.jpg"},
    { id: 65, name: "Celine Dion", rarity: "rare", icon: "assets/celineDion.jpg" },
    { id: 66, name: "Coldplay", rarity: "rare", icon: "assets/coldplay.jpg" },
    { id: 67, name: "Elton John", rarity: "rare", icon: "assets/eltonjohn.jpg" },
    { id: 68, name: "Eminem", rarity: "rare", icon: "assets/eminem.jpg"},
    { id: 69, name: "Frank Sinatra", rarity: "rare", icon: "assets/franksinatra.jpg"},
    { id: 70, name: "Jimmi Hendrix", rarity: "rare", icon: "assets/jimmihendrix.jpg" },
    { id: 71, name: "Led Zeppelin", rarity: "rare", icon: "assets/ledzeppelin.jpg" },
    { id: 72, name: "Lynyrd Skynyrd", rarity: "rare", icon: "assets/lynyrd.jpg" },
    { id: 73, name: "Madonna", rarity: "rare", icon: "assets/madonna.jpg" },
    { id: 74, name: "Nickelback", rarity: "rare", icon: "assets/nickelback.jpg"},
    { id: 75, name: "Ozzy Osbourne", rarity: "rare", icon: "assets/ozzy.jpg" },
    { id: 76, name: "Rammstein", rarity: "rare", icon: "assets/rammstein.jpg" },
    { id: 77, name: "Red Hot Chili Peppers", rarity: "rare", icon: "assets/rhcp.jpg" },
    { id: 78, name: "Simple Plan", rarity: "rare", icon: "assets/simpleplan.jpg" },
    { id: 79, name: "Skillet", rarity: "rare", icon: "assets/skillet.jpg" },
    { id: 80, name: "The Weeknd", rarity: "rare", icon: "assets/weeknd.jpg"},

    // EPIC
    { id: 81, name: "Bon Jovi", rarity: "epic", icon: "assets/Bonjovi.jpg" },
    { id: 82, name: "Aerosmith", rarity: "epic", icon: "assets/aerosmith.jpg"},
    { id: 83, name: "Green Day", rarity: "epic", icon: "assets/greenday.jpg" },
    { id: 84, name: "Ac/Dc", rarity: "epic", icon: "assets/acdc.jpg"},
    { id: 85, name: "BackStreet Boys", rarity: "epic", icon: "assets/backstreetboys.jpg"},
    { id: 86, name: "Creedence Clearwater Revival", rarity: "epic", icon: "assets/ccr.jpg" },
    { id: 87, name: "Linkin Park", rarity: "epic", icon: "assets/linkinpark.jpg"},
    { id: 88, name: "The Offspring", rarity: "epic", icon: "assets/offspring.jpg"},
    { id: 89, name: "Pink Floyd", rarity: "epic", icon: "assets/pinkifloyd.jpg"},
    { id: 90, name: "The Rolling Stones", rarity: "epic", icon: "assets/rollingstones.jpg" },
    { id: 91, name: "Taylor Swift", rarity: "epic", icon: "assets/taylorswift.jpg" },
    { id: 92, name: "Queen", rarity: "epic", icon: "assets/queen.jpg" },

    // LEGENDAIRE
    { id: 93, name: "The Beatles", rarity: "legendaire", icon: "assets/Beatles.jpg" },
    { id: 94, name: "Metallica", rarity: "legendaire", icon: "assets/metallica.jpg" },
    { id: 95, name: "Elvis Presley", rarity: "legendaire", icon: "assets/Elvis.jpg" },
    { id: 96, name: "Michael Jackson", rarity: "legendaire", icon: "assets/michaelJackson.jpg" },
];


const donneeAmeliorations = [
    { id: 1, name: "Nouveau Riff", prix: 10, points: 1 },
    { id: 2, name: "Seance de répétition", prix: 200, points: 3 },
    { id: 3, name: "Nouvelle Composition", prix: 800, points: 5 },
    { id: 4, name: "Soiree Découverte", prix: 3000, points: 8 },
];

const donneePalier = [
    { id: 1, name: "Garage Band", prix: 500, ptsAutoParSec: 10, description: "Débute ton aventure musicale + Les cartes rapportent des pts/sec"},
    { id: 2, name: "Premier concert", prix: 1500, ptsAutoParSec: 30, description: "Joue devant un petit public"},
    { id: 3, name: "Radio Locale", prix: 10000, ptsAutoParSec: 150, description: "Diffuse ta musique localement + Les cartes rapportent x10 fois plus de pts/sec"},
];